### PR TITLE
Dependency Upgrades

### PR DESCRIPTION
**Pull request by RachitKeertiDas**
Some siginificant dependency upgrades to keep the code base up to date, and hopefully make it faster

Currently a draft. Please do check for regressions.

Current Upgrades:
CRA to v4.0.3
Husky to v7
Eslint to v7
MUI to v4.0.3

Other minor safe upgrades to prop-types, prettier

To use the App despite ESLint Errors, please use the
environment variable ESLINT_NO_DEV_ERRORS=true

### CODE REVIEW

**Comment by peppermenta** [comment]
All of the UI buttons are now unresponsive. Can still access individual pages through the URL, but Navbar, Sidebar, and buttons on the individual pages are not functional

**Comment by RachitKeertiDas** [comment]
Fixed the linting errors now, and added a explicit eslint config to make sure we can use modern Javascript features.

Code should run now without the  `ESLINT_NO_DEV_ERRORS` environment variable being set.

**Comment by tarun-menta** [comment]
Noticed a white outline around the events in the calendar. This may have to do with the fact that we pulled the theme information from the theme provider, then passed that into the CSS rules of FullCalendar manually, since there was no way to set theme information for FullCalendar via their API

image

**Review by butter-chicken27 — APPROVED** [review]
Screenshot from 2022-02-23 12-24-14
White outline on the event boxes needs to be fixed in the calendar, can be raised as a ticket for another update. Core functionality is intact.

**Comment by RachitKeertiDas** [comment]
The outline issue is probably this:

https://github.com/fullcalendar/fullcalendar/issues/6512

fullcalendar got updated because of package-lock.json resolving to a higher version. The given workaround seems to work for our case though.

We can think of either using the css rule provided or maybe fixing full calendar to v5.6

**Comment by RachitKeertiDas** [comment]
The white outline should be gone now. I think we can safely land this PR now.

**Review by butter-chicken27 — APPROVED** [review]

**Pull request merged**
